live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#ff7878"
text = "#ffffff"

[colors.primary]
background = "#000000"

[cursor]
blink_interval = 350
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u0010"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Be"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "ø"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "¬"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "Å"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "Î"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001t"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "÷"
key = "Slash"
mods = "Command"

[[keyboard.bindings]]
chars = "«"
key = "Backslash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

# [[keyboard.bindings]]
# chars = "'"
# key = "Apostrophe"

# [[keyboard.bindings]]
# chars = "\""
# key = "Apostrophe"
# mods = "Shift"

# [[keyboard.bindings]]
# chars = "`"
# key = "Grave"

# [[keyboard.bindings]]
# chars = "~"
# key = "Grave"
# mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mode = "Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\t"
key = "Tab"
mods = "Command"

[[mouse.bindings]]
action = "ReceiveChar"
mouse = "Right"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "transparent"
dynamic_title = true
option_as_alt = "Both"
title = ""

[window.dimensions]
columns = 140
lines = 35

[window.padding]
x = 5
y = 5
